#! /bin/sh
# /etc/init.d/mlbService

### BEGIN INIT INFO
# Provides:          mlbClock
# Required-Start:    $all
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting mlbClock"
    # run application you want to start
    /home/pi/git/Citra/mlbServiceStart
    ;;
  stop)
    echo "Stopping mlbClock"
    # kill application you want to stop
    /home/pi/git/Citra/mlbServiceStop
    ;;
  *)B
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
